### ISSUE TITLE
Little syntax error in the latest release

### ISSUE THREAD

**Issue by Yemtex** [freifunk-darmstadt/fritz-tools#13]
Line 211 in the latest release is giving me a error.

Maybe this should be "if len(files) == 0", like the python compiler suggests.

But I also saw that the code in the master branch doesn't have this line anymore.

**Comment by mweinelt** [comment]
That expression was not very pythonic and has been replaced with `if not files:`

https://github.com/freifunk-darmstadt/fritz-tools/blob/master/fritzflash.py#L303

@blocktrron will need to do a new release in order to fix this.
