### ISSUE TITLE
recommend switch for flashing procedure (Linux)

### ISSUE THREAD

**Issue by niehauss** [freifunk-darmstadt/fritz-tools#14]
Hi,

flashing AVM hardware from a Linux computer seems a bit tricky. Discovery may work only if you connect the AVM hardware to a linux computer using a (dumb) switch inbetween.

Maybe a hint in the instructions would be helpful. 

Thnaks!

**Comment by Krisseck** [comment]
Yes, there is something wrong with the tool or instructions on Linux.

I tried for almost an hour to get it to autodiscover with Linux, no results. But on Windows I got it to to work on first try.

**Comment by herbetom** [comment]
I've added the idea to use a switch in #25 (only found this issue just now)
