### ISSUE TITLE
Add support for FRITZ!Box 7430

### ISSUE THREAD

**Issue by lustmue** [freifunk-darmstadt/fritz-tools#27]
I just completed the page for the FRITZ!Box 7430 (https://openwrt.org/toh/avm/avm_fritz_box_7430). HWRevision is 218. 

I suggest that you add support for FRITZ!Box 7430 to fritzflash.py (https://github.com/freifunk-darmstadt/fritz-tools/blob/master/fritzflash.py).

**Comment by blocktrron** [comment]
The 7430 is supported using eva_ramboot. Fritzflash only supports AVM devices which allow for writing to flash using the EVA bootloader.

**Comment by lustmue** [comment]
Instead of showing some cryptic error message when fritzflash.py is used on this model, I suggest to direct users to eva_ramboot.
