### ISSUE TITLE
Flash 7362SL returns "ftplib.error_temp: 426 Data connection closed"

### ISSUE THREAD

**Issue by KarstenDE** [freifunk-darmstadt/fritz-tools#6]
I try to flash a FritzBox 7362SL with the fritzflash.py via the following command:
`fritzflash.py --image openwrt-lantiq-xrx200-avm_fritz7362sl-squashfs-sysupgrade.bin`

The script ends with following return:
```
We will tell you when your device has finished installing Gluon (this may take a while).
Traceback (most recent call last):
  File "C:\RaspberryPi\Fritz\fritzflash.py", line 329, in <module>
    perform_flash(ip, imagefile)
  File "C:\RaspberryPi\Fritz\fritzflash.py", line 279, in perform_flash
    ftp.upload_image(file)
  File "C:\RaspberryPi\Fritz\fritzflash.py", line 59, in upload_image
    self.storbinary('STOR mtd1', image)
  File "C:\Python37\lib\ftplib.py", line 515, in storbinary
    return self.voidresp()
  File "C:\Python37\lib\ftplib.py", line 251, in voidresp
    resp = self.getresp()
  File "C:\Python37\lib\ftplib.py", line 244, in getresp
    raise error_temp(resp)
ftplib.error_temp: 426 Data connection closed
```

All at Windows 10

I already flashed multiple 7230 via the "--image' parameter.

Any ideas how to solve it?

**Comment by blocktrron** [comment]
As the 7362SL uses NAND flash, the chip itself can not be programmed by the bootloader itself. This is the same story for AVMs recovery.

AVM solves this by booting a ramdisk environment and programm the chip from there. This is fundamentally different from what we are currently doing with fritzflash.py. The 7320 works as it uses NOR chip. See also #4.

This approach means we need one image as the live environment and one image to be written to the devices flash. Maybe we can integrate the second into the first (and modify the commands used by firtzflash.py), but this is still a todo.

**Comment by KarstenDE** [comment]
Might be a good idea. But I just used the nice script for other purpose then usually foreseen because the different steps are a bit to complex.
