### ISSUE TITLE
SyntaxWaring at Windows 10, Python 3.8.0

### ISSUE THREAD

**Issue by christian-weiss** [freifunk-darmstadt/fritz-tools#9]
Syntax Warning in first line:
```
C:\Users\MyName\Downloads\fritzflash.py:211: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(files) is 0:

This program will help you installing Gluon, a widely used Firmware for Freifunk networks, onto your AVM device.
You can always find the most current version of this script at https://www.github.com/freifunk-darmstadt/fritz-tools

It is strongly recommended to only connect your computer to the device you want to flash.
Disable all other connections (Ethernet, WiFi/WLAN)!

Before we start, make sure you have assigned your PC a static IP Address in the Subnet of the device you want to flash.
The following example would be a completely fine option:

IP-Address: 192.168.178.2
Subnet: 255.255.255.0
Gateway: 192.168.178.1
DNS Servers: Leave blank

Once you're done, disconnect power from your AVM device, reconnect the power-supply and press enter.
```

Windows 10
Python 3.8.0:  https://www.python.org/ftp/python/3.8.0/python-3.8.0.exe

My first thought was, that this is because Windows 10 Tutorial is pointing to the Release page (10 month old script):
https://fritz-tools.readthedocs.io/de/latest/flashing/windows10.html#download-the-flash-script => 
https://github.com/freifunk-darmstadt/fritz-tools/blob/bc0ba30b80317b783cefbc34006e19d09c40afac/fritzflash.py#L211
while the Linux tutorial 
https://fritz-tools.readthedocs.io/de/latest/flashing/ubuntu_1804.html#download-the-flash-script 
is pointing to latest file from master (that statement has moved from line 211 to 255):
https://github.com/freifunk-darmstadt/fritz-tools/blob/master/fritzflash.py#L255

On Ubuntu 19.10 with 3.7.5rc1 i do not get this error on latest file from master. So maybe that syntax check was introduced in a newer python3 version.

**Comment by christian-weiss** [comment]
This SyntacWarning was introduced in Python version 3.8.0
https://docs.python.org/3/whatsnew/changelog.html
https://bugs.python.org/issue34850

**Comment by mweinelt** [comment]
Comparing identity of two integers is not good style, I'll fix this in a moment.

**Comment by mweinelt** [comment]
Fixed in 05c15319abc284f424d2bc515f1f92e8222f20f6.

Thanks!

**Comment by christian-weiss** [comment]
Any plans for a new release? (is master branch ready?)

**Comment by mweinelt** [comment]
I'm not familiar with the release process so I'll leave that to @blocktrron.

The master branch is ready to use, yes.
